### ISSUE TITLE
Doesn't make properly under go 1.12

### ISSUE THREAD

**Issue by davmaz** [mattn/golang-wasm-example#7]
Hi -- this is a great example when trying to learn WASM in go, but if I download the code and try to make, I get 
/main.go:37:41: undefined: js.NewCallback
./main.go:42:43: undefined: js.NewCallback
Makefile:6: recipe for target 'main.wasm' failed

Can you steer me in the right direction?
Thanks!

**Comment by syumai** [comment]
@davmaz Here's my PR to fix this.
https://github.com/mattn/golang-wasm-example/pull/6

@mattn Could you take a look at this PR when you have a time?
Thank you.
